<a href="https://colab.research.google.com/github/dffesalbon/machine-learning-tutorials/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
from time import process_time

In [ ]:
list = [i for i in range(10000)]
start = process_time()
list = [i + 5 for i in list]
end = process_time()
print(end- start);

0.001068748999999869


In [ ]:
np_array = np.array([i for i in range(10000)])
start = process_time()
np_array += 5
end = process_time()
print(end- start);

0.004863036000000154


In [ ]:
#list_np = np.array([1, 2, 3, 4, 5])
list_array = [1, 2, 3, 4, 5]
list_np = np.array(list_array)
print(list_np)
print(list_array)

print(type(list_np))
print(type(list_array))


[1 2 3 4 5]
[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
a = np.array([1, 2, 3, 4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [ ]:
b = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [ ]:
c = np.array([(1, 2, 3, 4), (5, 6, 7, 8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in NumPy arrays

In [ ]:
#array of zeroes

x = np.zeros((4, 5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#array of ones

y = np.ones((3, 3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#array of certain value

z = np.full((5, 4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create identity matrix

a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#create np array with random values
b = np.random.random((3, 4))
print(b)

[[0.53948893 0.95285292 0.40089946 0.99121532]
 [0.27429684 0.32497274 0.95119705 0.88117026]
 [0.1535811  0.87427585 0.16338656 0.75960484]]


In [ ]:
#create np array with random integer values with range

c = np.random.randint(1, 20, (3, 4))
print(c)

[[ 5  1 11  1]
 [15  7 18 15]
 [18  3 19 15]]


In [ ]:
# array of evenly spaced values -, specify number of values required
d = np.linspace(10, 30, 5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values -, specify steps

e = np.arange(5, 50, 5)
print(e)

[ 5 10 15 20 25 30 35 40 45]


In [ ]:
#convert list to np array
list2 = [10, 20 ,30 ,40, 50, 38]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50 38]


numpy.ndarray

Analysing an np array

In [ ]:
c = np.random.randint(10, 90, (5, 5))
print(c)

[[48 46 71 64 59]
 [46 61 43 58 73]
 [27 30 89 65 87]
 [65 40 14 25 53]
 [30 10 61 88 32]]


In [ ]:
# array dimensions
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
#number of elements
print(c.size)

25


In [ ]:
#checkign data type of values in array
print(c.dtype)

int64


Math operations

In [ ]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

print(list1 + list2) #concat or join 2 list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(10, 20, (3, 3))

print(a)
print(b)

[[0 7 0]
 [7 4 3]
 [0 8 7]]
[[10 18 14]
 [14 14 12]
 [18 14 13]]


In [ ]:
#math operation in np
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[10 25 14]
 [21 18 15]
 [18 22 20]]
[[-10 -11 -14]
 [ -7 -10  -9]
 [-18  -6  -6]]
[[  0 126   0]
 [ 98  56  36]
 [  0 112  91]]
[[0.         0.38888889 0.        ]
 [0.5        0.28571429 0.25      ]
 [0.         0.57142857 0.53846154]]


In [ ]:
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(10, 20, (3, 3))

print(a)
print(b)


[[7 2 6]
 [4 1 1]
 [3 0 4]]
[[16 11 10]
 [18 18 18]
 [11 13 14]]


In [ ]:
print(np.add(a ,b))

[[23 13 16]
 [22 19 19]
 [14 13 18]]


In [ ]:
print(np.subtract(a, b))

[[ -9  -9  -4]
 [-14 -17 -17]
 [ -8 -13 -10]]


In [ ]:
print(np.multiply(a, b))

[[112  22  60]
 [ 72  18  18]
 [ 33   0  56]]


In [ ]:
print(np.divide(a, b))

[[0.4375     0.18181818 0.6       ]
 [0.22222222 0.05555556 0.05555556]
 [0.27272727 0.         0.28571429]]


Array manipulation

In [ ]:
array = np.random.randint(0, 10, (2, 3))
print(array)

print(array.shape)

[[0 5 4]
 [5 9 6]]
(2, 3)


In [ ]:
#transpose

trans = np.transpose(array)
print(trans)

print(trans.shape)

[[0 5]
 [5 9]
 [4 6]]
(3, 2)


In [ ]:
array = np.random.randint(0, 10, (2, 3))
print(array)

print(array.shape)

[[1 8 6]
 [9 2 6]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)

print(trans2.shape)

[[1 9]
 [8 2]
 [6 6]]
(3, 2)


In [ ]:
#reshape

a = np.random.randint(0, 10, (2, 3))
print(a)

[[2 3 0]
 [4 6 8]]


In [ ]:
print(a.shape)

(2, 3)


In [ ]:
b = a.reshape(3, 2)
print(b)

print(b.shape)

[[2 3]
 [0 4]
 [6 8]]
(3, 2)
